# Generated by Django 3.2.5 on 2021-07-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Ad:')),
                ('comment', models.CharField(max_length=500, verbose_name='Rəy:')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Hazırlandığı tarix:')),
            ],
        ),
    ]
