# Generated by Django 3.2.5 on 2021-07-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
    ]
