# Generated by Django 3.2.5 on 2021-07-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210723_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
